import { useState, useRef } from 'react';
import { Button } from '@/components/ui/button';
import { ArrowLeft, Beaker, Pill, Zap, ExternalLink, BookOpen, Edit2, Trash2, Plus, FileDown } from 'lucide-react';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import type { Chapter, StudyItem, ItemType } from '@/types';

interface TopicPageProps {
  chapterId: string;
  topicId: string;
  chapters: Chapter[];
  onBack: () => void;
  onAddItemClick: () => void;
  onEditItem: (item: StudyItem) => void;
  onDeleteItem: (itemId: string) => Promise<void>;
}

export const TopicPage = ({ 
  chapterId, 
  topicId, 
  chapters, 
  onBack,
  onAddItemClick,
  onEditItem,
  onDeleteItem
}: TopicPageProps) => {
  const [selectedType, setSelectedType] = useState<ItemType | 'all'>('all');
  const [sortBy, setSortBy] = useState<'name' | 'date' | 'type'>('name');
  const [sortOrder, setSortOrder] = useState<'asc' | 'desc'>('asc');
  const [deleteItem, setDeleteItem] = useState<StudyItem | null>(null);
  const [isDeleting, setIsDeleting] = useState(false);
  const sectionRef = useRef<HTMLDivElement>(null);

  const chapter = chapters.find(ch => ch.id === chapterId);
  const topic = chapter?.topics.find(tp => tp.id === topicId);

  const getItemIcon = (type: ItemType) => {
    switch (type) {
      case 'molecule': return <Beaker className="w-5 h-5" />;
      case 'enzyme': return <Zap className="w-5 h-5" />;
      case 'medication': return <Pill className="w-5 h-5" />;
    }
  };

  const getItemColor = (type: ItemType) => {
    switch (type) {
      case 'molecule': return 'bg-blue-50 text-blue-600 border-blue-200';
      case 'enzyme': return 'bg-amber-50 text-amber-600 border-amber-200';
      case 'medication': return 'bg-emerald-50 text-emerald-600 border-emerald-200';
    }
  };

  // Filter and sort items
  let filteredItems = selectedType === 'all' 
    ? topic?.items || []
    : topic?.items.filter(item => item.type === selectedType) || [];

  // Sort items
  filteredItems = [...filteredItems].sort((a, b) => {
    let comparison = 0;
    switch (sortBy) {
      case 'name':
        comparison = a.name.localeCompare(b.name);
        break;
      case 'date':
        comparison = new Date(a.createdAt).getTime() - new Date(b.createdAt).getTime();
        break;
      case 'type':
        comparison = a.type.localeCompare(b.type);
        break;
    }
    return sortOrder === 'asc' ? comparison : -comparison;
  });

  const handleSort = (field: 'name' | 'date' | 'type') => {
    if (sortBy === field) {
      setSortOrder(sortOrder === 'asc' ? 'desc' : 'asc');
    } else {
      setSortBy(field);
      setSortOrder('asc');
    }
  };

  const handleDeleteConfirm = async () => {
    if (!deleteItem) return;
    setIsDeleting(true);
    try {
      await onDeleteItem(deleteItem.id);
      setDeleteItem(null);
    } catch (error) {}
    setIsDeleting(false);
  };

  const handleSharePDF = (item: StudyItem) => {
    // Create PDF content
    const content = `
      <html>
        <head>
          <style>
            body { font-family: Arial, sans-serif; padding: 40px; }
            h1 { color: #0B1E5B; border-bottom: 3px solid #00B8A9; padding-bottom: 10px; }
            .type { color: #00B8A9; font-weight: bold; text-transform: uppercase; }
            .scientific { color: #6B7280; font-style: italic; }
            .description { margin: 20px 0; line-height: 1.6; }
            .properties { background: #F6F7FA; padding: 20px; border-radius: 10px; }
            .property { display: flex; margin: 8px 0; }
            .key { font-weight: bold; width: 150px; color: #0B1E5B; }
            .value { color: #6B7280; }
            img { max-width: 300px; border-radius: 10px; margin: 20px 0; }
            .footer { margin-top: 40px; font-size: 12px; color: #9CA3AF; border-top: 1px solid #E5E7EB; padding-top: 20px; }
          </style>
        </head>
        <body>
          <h1>${item.name}</h1>
          <p class="type">${item.type}</p>
          ${item.scientificName ? `<p class="scientific">${item.scientificName}</p>` : ''}
          ${item.imageUrl ? `<img src="${item.imageUrl}" alt="${item.name}" />` : ''}
          <div class="description">
            <h3>Description</h3>
            <p>${item.description}</p>
          </div>
          ${item.properties?.length ? `
            <div class="properties">
              <h3>Properties</h3>
              ${item.properties.map(p => `
                <div class="property">
                  <span class="key">${p.key}:</span>
                  <span class="value">${p.value}</span>
                </div>
              `).join('')}
            </div>
          ` : ''}
          <div class="footer">
            Generated by PharmaStudy | Chapter: ${chapter?.name} | Topic: ${topic?.name}
          </div>
        </body>
      </html>
    `;
    
    const printWindow = window.open('', '_blank');
    if (printWindow) {
      printWindow.document.write(content);
      printWindow.document.close();
      printWindow.print();
    }
  };

  if (!chapter || !topic) {
    return (
      <div className="min-h-screen bg-[#F6F7FA] flex items-center justify-center">
        <div className="text-center">
          <p className="text-[#6B7280]">Topic not found</p>
          <Button onClick={onBack} className="mt-4">Go Back</Button>
        </div>
      </div>
    );
  }

  return (
    <div ref={sectionRef} className="min-h-screen bg-[#F6F7FA] py-8 px-4 sm:px-6 lg:px-8">
      <div className="max-w-7xl mx-auto">
        {/* Back Button & Header */}
        <div className="mb-6">
          <button
            onClick={onBack}
            className="flex items-center gap-2 text-[#6B7280] hover:text-[#0B1E5B] transition-colors mb-4"
          >
            <ArrowLeft className="w-5 h-5" />
            Back to {chapter.name}
          </button>

          <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
            <div>
              <div className="flex items-center gap-3 mb-2">
                <span className="text-sm text-[#6B7280] uppercase tracking-wider font-medium">
                  {chapter.name}
                </span>
              </div>
              <h1 className="text-3xl font-semibold text-[#0B1E5B]">{topic.name}</h1>
              <p className="text-[#6B7280] mt-2 max-w-2xl">{topic.description}</p>
            </div>
            <Button
              onClick={onAddItemClick}
              className="bg-[#00B8A9] hover:bg-[#00a396] text-white rounded-full px-6 flex items-center gap-2 self-start"
            >
              <Plus className="w-4 h-4" />
              Add Item
            </Button>
          </div>
        </div>

        {/* Filters & Sort */}
        <div className="flex flex-wrap items-center gap-3 mb-6">
          {/* Type Filter */}
          {(['all', 'molecule', 'enzyme', 'medication'] as const).map((type) => (
            <button
              key={type}
              onClick={() => setSelectedType(type)}
              className={`
                px-4 py-2 rounded-full text-sm font-medium capitalize transition-all
                ${selectedType === type
                  ? 'bg-[#00B8A9] text-white'
                  : 'bg-white text-[#0B1E5B] border-2 border-[#0B1E5B]/20 hover:border-[#00B8A9]'
                }
              `}
            >
              {type === 'all' ? 'All' : `${type}s`}
              {type !== 'all' && (
                <span className="ml-2 text-xs opacity-70">
                  {topic.items?.filter(i => i.type === type).length || 0}
                </span>
              )}
            </button>
          ))}

          <div className="w-px h-8 bg-[#0B1E5B]/10 mx-2" />

          {/* Sort Options */}
          <span className="text-sm text-[#6B7280]">Sort by:</span>
          {(['name', 'date', 'type'] as const).map((field) => (
            <button
              key={field}
              onClick={() => handleSort(field)}
              className={`
                px-3 py-1.5 rounded-full text-sm capitalize transition-all flex items-center gap-1
                ${sortBy === field
                  ? 'bg-[#0B1E5B] text-white'
                  : 'bg-white text-[#6B7280] border border-[#0B1E5B]/20 hover:border-[#0B1E5B]'
                }
              `}
            >
              {field}
              {sortBy === field && (
                <span className="text-xs">{sortOrder === 'asc' ? '↑' : '↓'}</span>
              )}
            </button>
          ))}
        </div>

        {/* Items Grid */}
        {filteredItems.length === 0 ? (
          <div className="text-center py-20 bg-white rounded-[22px] border-2 border-[#0B1E5B]/10">
            <div className="w-20 h-20 bg-[#0B1E5B]/5 rounded-full flex items-center justify-center mx-auto mb-4">
              <BookOpen className="w-10 h-10 text-[#0B1E5B]/40" />
            </div>
            <h3 className="text-xl font-medium text-[#0B1E5B]">
              {selectedType === 'all' ? 'No items yet' : `No ${selectedType}s yet`}
            </h3>
            <p className="text-[#6B7280] mt-2 mb-6">
              Add items to start building your study materials
            </p>
            <Button onClick={onAddItemClick} className="bg-[#00B8A9] hover:bg-[#00a396]">
              <Plus className="w-4 h-4 mr-2" />
              Add Your First Item
            </Button>
          </div>
        ) : (
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            {filteredItems.map((item) => (
              <div
                key={item.id}
                className="group bg-white rounded-[22px] border-2 border-[#0B1E5B] p-5 transition-all hover:shadow-[0_18px_0_rgba(11,30,91,0.10)] hover:-translate-y-1"
              >
                {/* Image */}
                {item.imageUrl && (
                  <div className="mb-4">
                    <img
                      src={item.imageUrl}
                      alt={item.name}
                      className="w-full h-40 object-cover rounded-xl"
                    />
                  </div>
                )}

                {/* Header */}
                <div className="flex items-start justify-between mb-4">
                  <div className={`w-10 h-10 rounded-full flex items-center justify-center border-2 ${getItemColor(item.type)}`}>
                    {getItemIcon(item.type)}
                  </div>
                  <div className="flex items-center gap-1 opacity-0 group-hover:opacity-100 transition-opacity">
                    <button 
                      onClick={() => onEditItem(item)}
                      className="p-2 hover:bg-[#00B8A9]/10 rounded-full transition-colors"
                      title="Edit item"
                    >
                      <Edit2 className="w-4 h-4 text-[#00B8A9]" />
                    </button>
                    <button 
                      onClick={() => setDeleteItem(item)}
                      className="p-2 hover:bg-red-50 rounded-full transition-colors"
                      title="Delete item"
                    >
                      <Trash2 className="w-4 h-4 text-red-500" />
                    </button>
                    <button 
                      onClick={() => handleSharePDF(item)}
                      className="p-2 hover:bg-blue-50 rounded-full transition-colors"
                      title="Print/Share PDF"
                    >
                      <FileDown className="w-4 h-4 text-blue-500" />
                    </button>
                  </div>
                </div>

                {/* Content */}
                <h3 className="text-lg font-semibold text-[#0B1E5B] mb-1">
                  {item.name}
                </h3>
                {item.scientificName && (
                  <p className="text-sm text-[#6B7280] italic mb-2">
                    {item.scientificName}
                  </p>
                )}
                <p className="text-[#6B7280] text-sm line-clamp-2 mb-4">
                  {item.description}
                </p>

                {/* Properties Preview */}
                {item.properties?.length > 0 && (
                  <div className="space-y-1 mb-4">
                    {item.properties.slice(0, 2).map((prop, idx) => (
                      <div key={idx} className="flex items-center gap-2 text-xs">
                        <span className="text-[#6B7280]">{prop.key}:</span>
                        <span className="text-[#0B1E5B] font-medium truncate">{prop.value}</span>
                      </div>
                    ))}
                    {item.properties.length > 2 && (
                      <span className="text-xs text-[#00B8A9]">
                        +{item.properties.length - 2} more
                      </span>
                    )}
                  </div>
                )}

                {/* Actions */}
                <div className="flex items-center justify-between pt-4 border-t border-[#0B1E5B]/10">
                  <span className="text-xs text-[#6B7280] capitalize">
                    {item.type}
                  </span>
                  <button 
                    onClick={() => onEditItem(item)}
                    className="flex items-center gap-1 text-[#00B8A9] text-sm font-medium hover:underline"
                  >
                    View Details
                    <ExternalLink className="w-3 h-3" />
                  </button>
                </div>
              </div>
            ))}
          </div>
        )}

        {/* Delete Confirmation Dialog */}
        <Dialog open={!!deleteItem} onOpenChange={() => setDeleteItem(null)}>
          <DialogContent className="sm:max-w-md rounded-[22px] border-2 border-red-200">
            <DialogHeader>
              <DialogTitle className="text-xl font-semibold text-red-600">Delete Item?</DialogTitle>
              <DialogDescription className="text-[#6B7280]">
                This will permanently delete <strong>{deleteItem?.name}</strong>. This action cannot be undone.
              </DialogDescription>
            </DialogHeader>
            <div className="flex gap-3 pt-4">
              <Button
                variant="outline"
                onClick={() => setDeleteItem(null)}
                className="flex-1 h-12 rounded-full"
              >
                Cancel
              </Button>
              <Button
                onClick={handleDeleteConfirm}
                disabled={isDeleting}
                className="flex-1 h-12 bg-red-500 hover:bg-red-600 text-white rounded-full"
              >
                {isDeleting ? 'Deleting...' : 'Delete'}
              </Button>
            </div>
          </DialogContent>
        </Dialog>
      </div>
    </div>
  );
};
